### ISSUE TITLE
Add incident/test ID to lead data 

### ISSUE THREAD

**Issue by walker** [OpenDataSTL/health-hack-weekend#2]
Is there an incident or test ID number that can be provided with each row to help ensure uniqueness each time a new data set would be provided in a production environment?

**Comment by eleanortutt** [comment]
I wrote Matt, Carl, & Leila about this question to see if we can get an answer!

We do have the unique IDs for each child, so I think I work around could be to add a test ID field that combined child ID and test date.  I doubt a child is getting tested twice on the same date?

**Comment by walker** [comment]
@eleanortutt I doubt that a child is, but this is demo data (because they can't release real-world data). So it would be important that we maintain production data similarity.

Of course, this data can be handled upon parse/import by using the DCN/date feature, but I just wanted to check and see if an ID was available in production. If it's not, I wouldn't put it in this set.

**Comment by eleanortutt** [comment]
OK, the answer is that a unique ID for tests doesn't seem to exist.  

Carl: "My guess is no - just date of test."

Matt: "To my knowledge, there's no unique ID for individual tests. As Carl said, just test date."

**Comment by walker** [comment]
Ok.
