### ISSUE TITLE
What data was the geocode generated from for health inspections?

### ISSUE THREAD

**Issue by marigolds6** [OpenDataSTL/health-hack-weekend#6]
The geocoded json has a phone number in it, the csv does not.  
Where did the phone number come from? And how was the geocoding generated?  
(So we can add it to a repeatable script.)

**Comment by schwuw** [comment]
I was working with the data and here are the other questions I had (I've already forwarded to Leila, Health dept person who presented idea):

(I first attempted to standardize the addresses and noticed a bunch of zip codes needed updating, not all phone numbers are complete, so addresses are outside of the city boundaries. Need to clean some of the data.)

Are there unique IDs to each location? Each business has a unique business ID but the businesses often have multiple franchise locations, i.e. Burger King on Delmar and Burger King on Hampton.

Are inspections specific to the location or to the business? Related to the previous question, the food inspections list a business name, but don't list the address. Ideally the inspections list would have the unique location ID added.

Inspections for franchises are not connected are they? i.e. a FAIL at one Burger King doesn't affect all the locations.

What is the Grade scale? i.e. 90-100="A"?  80-89="B"?  Just trying to establish the grade levels.

Could the data be hosted on a City web server? I'm sure we could host a file initially, but eventually Yelp would want to establish a permanent connection to a city web server for ongoing updates.

I think this gets us far enough for an initial upload. There is a question of which establishments should be posted, as not all are publicly available, and how food trucks should be handled.  I was also curious about businesses with addresses outside of the City, located in Illinois or the County, and how that should be handled.

**Comment by eleanortutt** [comment]
Brett - The phone number is in the .csv file, so I'm not sure what your question is there.

I just used the built in MMQGIS google geocoder in QGIS to do a rough geocode of the .csv - the intention wasn't for that to be the "way this is done" for the LIVES standard work - I agree we want a script to start with the raw .csv the health department can export.  I just thought some geojson would be helpful for people who might want to use the establishments data for some other unpredictable-in-advance purpose this weekend.

**Comment by marigolds6** [comment]
Oh... I was using the github viewer and it was chopping off a bunch of fields. I can see them in the raw csv :)
